version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/tec-frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "@yasser172/tec-sdk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@yasser172/tec-shared"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
