import type { Metadata } from 'next';
import { LIVE_DOMAINS } from '@/domains/_registry';
import PioneersClient from './PioneersClient';

// Public onboarding page for early Pioneers — one link that gathers every TEC
// app + the 3-step engagement guide, so a Pioneer can open each app in Pi Browser
// and complete the login engagement that a Pi domain claim needs.
// Public by design (NOT in middleware PROTECTED_ROUTES) — no auth to view.
// The app count is derived from the LIVE domain registry so the copy never drifts.
const TITLE = 'TEC Founding 100 — Become a Founding Pioneer';
const DESCRIPTION = `Be one of TEC’s first 100 Founding Pioneers. Open each app in Pi Browser, log in with Pi, and try one action — ${LIVE_DOMAINS.length} apps live on Pi Mainnet, one identity, real Pi payments. The Founding badge is earned, never bought.`;

// OpenGraph + Twitter so a shared /pioneers link renders a branded card (the OG
// image is generated by opengraph-image.tsx / twitter-image.tsx). metadataBase is
// set in the root layout, so the relative canonical resolves to the deployed host.
export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: '/pioneers' },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: '/pioneers',
    siteName: 'TEC',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function PioneersPage() {
  return <PioneersClient />;
}
